# Generated by Django 3.1.2 on 2020-10-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('startDate', models.DateField(default='0001-01-01')),
                ('endDate', models.DateField(default='0001-01-01')),
                ('miles', models.FloatField(default=0)),
                ('elevationGain', models.FloatField(default=0)),
                ('elevationLoss', models.FloatField(default=0)),
                ('description', models.TextField(default='')),
                ('starred', models.BooleanField(default=False)),
                ('image', models.ImageField(default=None, upload_to='img/')),
            ],
        ),
    ]
