# Generated by Django 3.1.1 on 2020-10-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miles', models.FloatField()),
                ('elevationGain', models.FloatField()),
                ('elevationLoss', models.FloatField()),
                ('description', models.TextField()),
                ('starred', models.BooleanField()),
            ],
        ),
    ]
