# Generated by Django 3.1.2 on 2020-10-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='hike',
            name='elevationGain',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='hike',
            name='elevationLoss',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='hike',
            name='endDate',
            field=models.DateField(default='0001-01-01'),
        ),
        migrations.AlterField(
            model_name='hike',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='hike',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='hike',
            name='miles',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='hike',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='hike',
            name='starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hike',
            name='startDate',
            field=models.DateField(default='0001-01-01'),
        ),
    ]
