# Generated by Django 3.1.2 on 2020-11-19 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_togglevar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToggleVar',
        ),
    ]
