# Generated by Django 3.1.2 on 2020-11-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20201129_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='tag',
            field=models.TextField(blank=True, default=''),
        ),
    ]
