# Generated by Django 3.1.2 on 2020-11-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20201129_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hike',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='hike',
            name='image2',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='hike',
            name='image3',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
